### ISSUE TITLE
Jmatio reads large file exceptions

### ISSUE THREAD

**Issue by tanhuang2016** [codemercenary/JMatIO#5]
jmatio-1.0

Exception in thread "main" java.lang.IllegalArgumentException: Negative size
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:865)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:287)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:154)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:102)
	at com.hw.parse.prob.tocassandra.Test.main(Test.java:23)

![图片](https://user-images.githubusercontent.com/38677722/95697708-2e729b80-0c72-11eb-8a0b-3927b7b1013c.png)

prob_20200913_12.mat file size is 3.11GB

How can I solve this problem? Thank you

**Comment by nedtwigg** [comment]
History: JMatIO was forked as [`MatFileRW`](https://github.com/diffplug/matfilerw), which fixed a lot of bugs, and has the same API as JMatIO.  Then https://github.com/HebiRobotics/MFL came along, which is a new API, but much better.

My guess is that switching to MatFileRW is easy, and might fix your problem, but probably not.  Switching to MFL will almost definitely fix your problem, but it will take some work.
